# fly.toml app configuration file generated for shamiri-billowing-dew-7238 on 2025-03-20T10:44:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shamiri-journal'
primary_region = 'jnb'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy && npx prisma db seed'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
